### ISSUE TITLE
How to associate data specific to an individual path (vs to a template)

### ISSUE THREAD

**Issue by misner** [markdalgleish/static-site-generator-webpack-plugin#134]
I have multiple pages using the same template:

**webpack.config.js**

```
var template = ejs.compile(fs.readFileSync(__dirname + '/template.ejs', 'utf-8'))
var paths = [
  '/page1',
  '/page2'
 'and so on...'
];

new StaticSiteGeneratorPlugin({
      entry: 'index.js',
      paths: paths,
      locals: {
        template: template
      }
    })

```

**index.js**

```
module.exports = function(locals) {
  return Promise.resolve(locals.template({ html: '<h1> this is cool' + locals.path + '</h1>' }));
};
```

But I wonder is it possible to attache data that is not specific to all the paths but to each page, for example that happens a lot with html title or metas.

I would like to associate different metas and title for each page. For example:

> 
> /page1 has
> title: title of page1
> meta: 'this is a nice meta for page 1'
> 
> /page1 has
> title: title of page2
> meta: 'this is a nice meta for page 2'

Should I , and is it possible, to change the path from an array (as shown in the Set up Guide) into a array of jsons so that I can display data specific to each page like so ?

```
var template = ejs.compile(fs.readFileSync(__dirname + '/template.ejs', 'utf-8'))
var paths = [
  { path: /page1,
    title: 'title of page 1',
    meta: ' this is a nice meta for page 1'
  },
 { path: /page2,
    title: 'title of page 2',
    meta: ' this is a nice meta for page 2'
  }
 'and so on...'
];
```

**Comment by lifeinchords** [comment]
Any resolution? I'd like to do this as well.

**Comment by misner** [comment]
Sorry could not get it to work:(
