### ISSUE TITLE
Weird error message on some platforms

### ISSUE THREAD

**Issue by omnidan** [markdalgleish/static-site-generator-webpack-plugin#17]
This plugin works fine on my macbook pro (OS X 10.10) but doesn't seem to work on Debian (not sure if it's really related to the platform but that's the only difference I could think about).

The error message isn't really helpful:

```
ERROR in Symbol is not defined
```

**Comment by omnidan** [comment]
The problem seems to have been a ES6 `for .. of` loop, replacing it with a normal ES5 `for` loop fixed the issue. You should push/display `err.stack` instead of `err`, by the way. The current error output is really not useful at all.

**Comment by markdalgleish** [comment]
This is a general Node issue when code assumes a global like `Symbol` exists.

**Comment by omnidan** [comment]
@markdalgleish would it be possible to improve the error output or does it come from node too?

**Comment by markdalgleish** [comment]
No, this is outside my control, unfortunately.

**Comment by omnidan** [comment]
Aw that sucks. Hopefully this issue helps people figure out what's wrong then :sweat_smile:
