### ISSUE TITLE
Serve static pages by webpack-dev-server

### ISSUE THREAD

**Issue by VaclavSynacek** [markdalgleish/static-site-generator-webpack-plugin#18]
This is probably not an issue, but feature request. Is there a way to serve html files generated by this plugin by webpack-dev-server dynamically? I can get the dev server to serve already generated files from the output directory, but I would like the webpack-dev-server to rerun generation by the plugin whenever sources change and serve this up-to-date html files. Any ideas how to do this?

**Comment by teodragovic** [comment]
I just had this same problem myself and found that soulution is to use BrowserSync instead of Webpack dev server. This is my `webpack.config.js`:

```
const StaticSiteGeneratorPlugin = require('static-site-generator-webpack-plugin');
const BrowserSyncPlugin = require('browser-sync-webpack-plugin');

const path = require('path');
const data = require('./app/data');

module.exports = {

    entry: {
        main: './app/entry.js'
    },

    output: {
        filename: 'bundle.js',
        path: path.join(__dirname, 'build'),
        libraryTarget: 'umd',
        publicPath: '/'
    },

    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                include: [
                    path.join(__dirname, 'app')
                ],
                query: {
                    presets: ['es2015', 'react']
                }
            },
        ]
    },

    plugins: [
        new StaticSiteGeneratorPlugin('main', data.routes, data),
        new BrowserSyncPlugin({
            host: 'localhost',
            port: 3000,
            server: { baseDir: ['build'] }
        })
    ]
}
```

...and when I run `webpack --watch` my `build/` directory is served on localhost:3000 and files are regenerated on change.

**Comment by dewwwald** [comment]
Wait. I don't agree with using browser sync to solve this issue. What if I want the HMR module?

**Comment by dewwwald** [comment]
This issue seem related to my problem:

When I remove static site generator from my webpack config I get the following error. Anyone have any advice on how I can track the issue down?

```
ERROR in ReferenceError: self is not defined
    at Object.<anonymous> (static:18380:18)
    at Object.<anonymous> (static:18416:30)
    at __webpack_require__ (static:672:30)
    at fn (static:98:20)
    at Object.<anonymous> (static:36502:1)
    at __webpack_require__ (static:672:30)
    at module.exports (static:718:39)
    at static:721:10
    at webpackUniversalModuleDefinition (static:3:20)
    at static:10:3
```

**Comment by wi-ski** [comment]
Im having the same problem

**Comment by Birowsky** [comment]
Try adding `inline: false` in devServer.

https://stackoverflow.com/a/41492420/592641

**Comment by NateFerrero** [comment]
@Birowsky brilliant - that solved my problem.

**Comment by VaclavSynacek** [comment]
I do not need this feature any more others seem happy with the workarounds discussed => closing this almost 4 years old feature request.

**Comment by cclusetti** [comment]
> Try adding `inline: false` in devServer.
> 
> https://stackoverflow.com/a/41492420/592641

What's the equivalent workaround in webpack5?
