### ISSUE TITLE
UTF-8 support?

### ISSUE THREAD

**Issue by omnidan** [markdalgleish/static-site-generator-webpack-plugin#19]
There seems to be an issue with UTF-8 encoded data.

When starting with `webpack-dev-server`, it works fine. When running it through this plugin to generate a static HTML page, it seems to break the encoding.

The contents of the file seem to be fine, but when I open the HTML in a browser it's broken. I'm processing the static HTML to a PDF later, which means it's also broken there.

**Comment by VaclavSynacek** [comment]
Could you please post the code that is used to generate the output, the output html and webpack config file?

I have some wild guesses where the problem might be, but it is hard to tell without the code. First ideas:
* output html does not declare the encoding in a way your browser understands (not related to this plugin)
* you are using some new ES6 unicode features + babel, but this plugin ignores babel loader (might be a special case of #20 
* something else

**Comment by omnidan** [comment]
@VaclavSynacek seems like `<meta charset="UTF-8">` fixes the issue, so your first idea was right :grin:
