### ISSUE TITLE
Best way to not include server rendering in client build

### ISSUE THREAD

**Issue by calebmer** [markdalgleish/static-site-generator-webpack-plugin#38]
Is there a good way to not include the default export in the optimized client build? The way I'm doing this now is defining two entry points `main` and `static` where this plugin uses `static` to generate the pages. However, I'm unsure how negatively this effects webpack's performance (now it has to build a lot of the same things twice). Is there a good idiomatic solution to avoiding this? If there is could it be included in the `README`?

**Comment by jacobmarshall** [comment]
Not too sure why this issue was closed, did you find a solution @calebmer? I am wondering the same thing.

**Comment by calebmer** [comment]
I personally moved on to another tool so I closed this issue to reduce noise and I no longer was in the position to provide valuable input 😊

I'd recommend opening a new issue, reference it though so I can subscribe.
