### ISSUE TITLE
route params?

### ISSUE THREAD

**Issue by Akenne** [markdalgleish/static-site-generator-webpack-plugin#39]
is there anyway to do this?

such as /about/:id

**Comment by markdalgleish** [comment]
This project generates a static site, so dynamic route params don't work at runtime. You can use a router in your development environment, and ensure you statically generate all the pages you need. I've done this myself using React Router and it works well, but again, you need to provide the complete list of URLs to generate—the router won't work at runtime, at least on the first render.

**Comment by steven-haddix** [comment]
@markdalgleish Any chance you have an example of what this would look like? Can you actually do it in the router or do you have to have it in the webpack config? 

As far as I can tell only one file gets written per entry in the webpack config. So unless theres something building a list of pages in the config it wouldn't get built?
