### ISSUE TITLE
GatsbyJs + react-translate =  context is lost during build

### ISSUE THREAD

**Issue by mtt87** [markdalgleish/static-site-generator-webpack-plugin#77]
I did a lot of digging and I think the issue is related to this plugin.

In `gatsby-browser.js`
```
import React from 'react';
import { TranslatorProvider } from "react-translate";
const translations = require('./i18n');

exports.wrapRootComponent = (Root) => {
  const Wrapper = () => (
    <TranslatorProvider translations={translations}>
      <Root />
    </TranslatorProvider>
  )
  return Wrapper;
}
```

In my `Home.js` component
```
import React from 'react';
import { translate } from "react-translate";
const Home = ({ t }) => {
  return (
    <div>
      {t("tagline1")}
    </div>
  );
}
export default translate("Home")(Home);
```

It works great during development but then when the project has to be built with `gatsby build` using this webpack plugin, it's failing because seems like the `context` is lost
```
Error: TypeError: translator is not a function
```

I think this might be related to the same issue people had with the new `react-router` `context`, do you have any advice how to fix this?

Is `static-site-generator-webpack-plugin` supposed to work with a `<Provider>` component in React that is adding a `context` to all the children elements?

Thank you 😄

**Comment by mtt87** [comment]
It wasn't related to this plugin

**Comment by danniehakan** [comment]
@mtt87 I'm having the same issue, how did you solve it?

**Comment by mtt87** [comment]
Check here I remember it wasn't related to this plugin:
https://github.com/gatsbyjs/gatsby/issues/688
