### ISSUE TITLE
Run client side

### ISSUE THREAD

**Issue by peduarte** [markdalgleish/static-site-generator-webpack-plugin#8]
Hello,

I've been playing around with this Static Site Generator for a while, thanks for the work you've put in! It's a great idea. 👍

I do have a few questions though, and I hope someone can lead me towards the right direction.

Me and @henriquea have spent a few hours trying to get client side code to run.

By *client side code*, I mean basic React method, such as:
```
componentDidMount()
```
```
setState()
```

I guess, that I was expecting this to work on the client side as well as just having the initial load being static.

Maybe I am approaching this the wrong way, but can anyone help?

I couldn't find anything on the documentation about not being able to run it client side :/

PS: Also, if using with any external libraries, such as `fastClick` that checks for `navigator` or `window` it breaks, for obvious reasons. 😒

/cc @KyleAMathews I saw your feedback on https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/2 and though they were very relevant. I was wondering if maybe you'd be able to help me? Or tell me if Gatsby is an alternative? Thanks!

**Comment by KyleAMathews** [comment]
Hey @peduarte and @henriquea. Yes, this is exactly what Gatsby is for. It handles both statically rendering your component to an `index.html` as well as generating a `bundle.js` that auto-mounts upon loading and runs your React.js code client-side. It uses this plugin under the hood to do the static page generation.

**Comment by peduarte** [comment]
@KyleAMathews Awesome, man. Thanks for replying :) I will give Gatsby a go now.

**Comment by KyleAMathews** [comment]
@peduarte awesome! Ping me if you have any trouble.

**Comment by henriquea** [comment]
Thanks for the quick response @KyleAMathews 😊

**Comment by KyleAMathews** [comment]
@peduarte @henriquea Have a chance to try Gatsby? Curious how it went.

**Comment by markdalgleish** [comment]
The React Router example in the readme shows how you can do universal rendering with this plugin. I'm closing this issue, but please re-open if this didn't answer your question or if the readme isn't clear to you.
