### ISSUE TITLE
Support non index.html files

### ISSUE THREAD

**Issue by KyleAMathews** [markdalgleish/static-site-generator-webpack-plugin#9]
Right now if you pass in a path like `about.html`, the plugin creates a page at `about.html/index.html`. It'd be nice to make this configurable.

This came up in Gatsby at https://github.com/gatsbyjs/gatsby/issues/14

**Comment by VaclavSynacek** [comment]
I'm sorry, but I would vote this down :-1: . Or at least label this as new request, low priority. static-site-generator-webpack-plugin states it "works particularly well with react-router" and react-router is all about clean urls without html in them (not stated, but I have never seen a single example with .html routes). So in the above example, what is the use case that needs "about.html", when the route can simply be clean "about" and handled by the current implementation like "about/index.html'?

**Comment by flosse** [comment]
I think it makes a lot of sense to support non index.html files because you can build static sites without JS :)

**Comment by markdalgleish** [comment]
This has been fixed in `v2.0.0` of static-site-generator-webpack-plugin :tada:
